# Generated by Django 3.2.2 on 2021-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_hospitals_noofseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('consulttext', models.CharField(max_length=200)),
                ('doctorName', models.CharField(max_length=200)),
            ],
        ),
    ]
