# Generated by Django 3.2.2 on 2021-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='casestudydata',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
