# Generated by Django 3.2.2 on 2021-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patients_casestudydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hospitalName',
            field=models.CharField(default='No Name', max_length=200),
        ),
    ]
